# Netlify Configuration สำหรับ Kim Pai Repair Flow

[build]
  # Build command
  command = "npm run build"
  
  # Output directory
  publish = "dist"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--production=false"

# SPA Routing - redirect ทุก route ไปที่ index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers สำหรับ Security และ Performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# API Headers (ถ้ามี API routes)
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Form handling (ถ้าใช้ Netlify Forms)
# [[redirects]]
#   from = "/contact"
#   to = "/contact-success"
#   status = 200
#   conditions = {Role = ["admin"]}

# Function settings (ถ้าใช้ Netlify Functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Dev settings
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"