name: React Vite Deployment

on:
    push:
        branches: ["main", "feat/cicd*"]

jobs:
    prepare:
        runs-on: topdev
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup node version
              uses: actions/setup-node@v3
              with:
                  node-version: 20.13.1

            - name: install dependencies
              run: |
                  npm install --legacy-peer-deps

            - name: Build project
              run: |
                  igs-vault write /stag/data/${{ github.event.repository.name }} .env
                  igs-vault append /global/data/stag/windows .env
                  npm run build

            - name: Clean project
              run: |
                  npx rimraf ./node_modules
                  npm install --production --legacy-peer-deps

    deploy:
        runs-on: topdev
        needs: prepare
        env:
            appName: ${{ github.event.repository.name }}

        steps:
            - name: Set destination path and script
              run: |
                  $destination = "E:\Deploy\Pm2\${{ github.event.repository.name }}"
                  mkdir -Force $destination | Out-Null
                  echo "destination=$destination" >> $env:GITHUB_ENV
                  echo "deploy_script=deploy.bat" >> $env:GITHUB_ENV

            - name: Download deploy script
              run: |
                  Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Toppingeni/deploy-script/main/deploy.bat" -OutFile "deploy.bat"

            - name: Stop application
              run: ./deploy.bat stop ${{env.appName}}

            - name: Create directories and copy files
              run: |
                  mkdir -Force "$env:destination\dist"
                  mkdir -Force "$env:destination\node_modules"
                  Copy-Item -Path ".\dist\*" -Destination "$env:destination\dist\" -Recurse -Force
                  Copy-Item -Path ".\node_modules\*" -Destination "$env:destination\node_modules\" -Recurse -Force
                  Copy-Item -Path ".\package.json" -Destination "$env:destination\" -Force
                  Copy-Item -Path ".\vite.config.ts" -Destination "$env:destination\" -Force
                  if (Test-Path ".env") {
                      Copy-Item -Path ".env" -Destination "$env:destination\" -Force
                  }

            - name: Copy deploy script
              run: Copy-Item -Path ".\deploy.bat" -Destination "$env:destination\" -Force

            - name: Start application
              run: |
                  cd "$env:destination"
                  ./deploy.bat start ${{env.appName}}

            - name: Save Pm2
              run: |
                  pm2 save --force

    alert:
        runs-on: topdev
        needs: deploy
        steps:
            - name: Notify via Telegram Success
              if: success()
              run: |
                  Invoke-RestMethod -Uri "http://192.168.55.38:51104/api/telegram/sendMessage" `
                  -Method POST `
                  -Headers @{ "Content-Type" = "application/json" } `
                  -Body '{"message": "${{github.repository}} - ${{github.workflow}} - Success"}'

            - name: Notify via Telegram Failure
              if: failure()
              run: |
                  Invoke-RestMethod -Uri "http://192.168.55.38:51104/api/telegram/sendMessage" `
                  -Method POST `
                  -Headers @{ "Content-Type" = "application/json" } `
                  -Body '{"message": "${{github.repository}} - ${{github.workflow}} - Failure"}'